{% set version = "1.5.4" %}
{% set name = "mpfi" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://gforge.inria.fr/frs/download.php/file/37331/mpfi-{{ version }}.tar.bz2
  sha256: 2383d457b208c6cd3cf2e66b69c4ce47477b2a0db31fbec0cd4b1ebaa247192f

build:
  number: 1001
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('mpfi', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - libtool

  host:
    - gmp
    - mpfr

  run:
    - gmp
    - mpfr

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}${SHLIB_EXT}  # [unix]

about:
  home: http://mpfi.gforge.inria.fr/
  license: LGPL 3
  license_file: COPYING
  summary: A multiple precision interval arithmetic library based on MPFR
  dev_url: https://gforge.inria.fr/scm/?group_id=157

extra:
  recipe-maintainers:
    - isuruf
    - marcelotrevisani
