travis:
  secure:
    BINSTAR_TOKEN: lAVZZjY4NGNy7D1UCs7vD7hddw8hWdvhAOI6nsZ3DCaT0XZI8WVhWlk8L3/owSgwkQG7breoR+x/VPpg639zs3DSHimVJsUu7RlyMn01x46ftzHDitNQhY1iv7y7sE/oALGlxFn79TG9xHnLJdJPcGmPEFS4ZXz/Ww62AcS5FYs8KuVP44JYBeR1WpO8WoPWvB8GgNQVFvh3g0M3SGXPQbzFMK+0QlzsLXm4Ly25d+f7QuR9g9j2rGOe65C1U4M2bJ1Dn3cnpyFUpfPuxePrhQQeyyXu+ywbRXrWFrRPbAKsUkxTH9A2Wc2WBDY2SI8LEt0QGIogVaMY1NVS5LSem6Oe/eEzDF+hFa+wDe6Je97yCxzvEHZ4w/DKIMb1py6xmza1wwFoIIQJbievPtV7kGk2nOixyWii5wc3aigCsrvsHG91a8GXgXJXoezvQNyXWbriVMYpMW6r3z89cywXu5WBoiKVM6//D2aOsCwuVOgLix+yWqE2sISOFGvEjd8KyF1p/68z8zhEzoFaNXmsNm/uNLSgzS8ghcO2OmJ9Ab9OrgVtqLmiy4H1gpShnsYkeZYrX/8Fk2TGc/0oAu3XrNumf/crV7xJl+2cRpzNnrBLjJ4JkQkDA1ubHzNDMuF/edk4IE44anIsfAHoedZJhXp/vvfLGIoZLzgLIsSThJQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
